# NUMPY BASICS

                                                                                                  Written by,
                                                                                                  Shubham Joshi

                                                                                                  Presented and Compiled by,
                                                                                                  Pranav G 
                                                                                                  Pravveen Murugesan V


NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects that supports 'vectorised code' paradigm (ie) operations that are performed on multiple components at the same time. For example, we have a matrix or array, if we want to square each term, we use loops in normal programming paradigm whereas in vectorized code paradigm, we just square the matrix or array object.

Numpy Arrays : A homogenous multidimensional construct

Index in numpy array starts with '0'

In [3]:
import numpy as np 

In [4]:
array_1d = np.array([1,2,3,4]) #This is an example of one dimensional array

array_2d = np.array([[1,2,3],[4,5,6]]) #This is an example of two dimensional array

In [5]:
type(array_1d)

type(array_2d)

numpy.ndarray

### Advantages of numpy:

1.You can write vectorized code on Numpy arrays, not on lists, which is convenient to read and write and also concise.

2.Numpy is much faster than standard python ways.

3.Vectorized code typically does not contain explicit looping, indexing etc ( all of this happens behind the scenes in a precompiled C code)


In [7]:
ar1=np.array([1,2])

ar2=np.array([3,4])

ar3=ar1* ar2

print(ar3)

[3 8]


### Ways to create numpy arays:

In [12]:
print(np.array([1,23,45])) #Using List
print(np.array((1,2,'a','b')))  #Using Tuple
 


[ 1 23 45]
['1' '2' 'a' 'b']


In [4]:
print(np.ones((4,3),int)) 

"""numpy.ones(shape, dtype=None, order='C')
Return a new array of given shape and type, filled with ones"""

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


"numpy.ones(shape, dtype=None, order='C')\nReturn a new array of given shape and type, filled with ones"

In [5]:
print(np.zeros((2,4),int))

"""numpy.zeros(shape, dtype=float, order='C')
Return a new array of given shape and type, filled with zeros."""

[[0 0 0 0]
 [0 0 0 0]]


"numpy.zeros(shape, dtype=float, order='C')\nReturn a new array of given shape and type, filled with zeros."

In [17]:
np.random.random() #Return random floats in the half-open interval [0.0, 1.0).

0.7833716782044559

In [6]:
print(np.arange(10,100,5)) #Creates a np array with incremental values of fined step size

"""numpy.arange([start, ]stop, [step, ]dtype=None)
Return evenly spaced values within a given interval.
Values are generated within the half-open interval [start, stop)"""


[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


'numpy.arange([start, ]stop, [step, ]dtype=None)\nReturn evenly spaced values within a given interval.\nValues are generated within the half-open interval [start, stop)'

In [7]:
print(np.linspace(15,18,25)) 

"""numpy.linspace(start, stop, num, endpoint=True, retstep=False, dtype=None)[source]
Return evenly spaced numbers over a specified interval
"""

[15.    15.125 15.25  15.375 15.5   15.625 15.75  15.875 16.    16.125
 16.25  16.375 16.5   16.625 16.75  16.875 17.    17.125 17.25  17.375
 17.5   17.625 17.75  17.875 18.   ]


'numpy.linspace(start, stop, num, endpoint=True, retstep=False, dtype=None)[source]\nReturn evenly spaced numbers over a specified interval\n'

### Reshaping the numpy array

In [21]:
a = np.arange(6)
print(np.reshape(a, (2, 3)))

"""Parameters:
a : array_like
Array to be reshaped.

newshape : int or tuple of ints
The new shape should be compatible with the original shape"""

[[0 1 2]
 [3 4 5]]


'Parameters:\na : array_like\nArray to be reshaped.\n\nnewshape : int or tuple of ints\nThe new shape should be compatible with the original shape'

### Subseting np arrays:

In [24]:
print(array_1d[2])  #specific element index

print(array_1d[[2,1,3]]) # Accessing using index of the element

3
[3 2 4]


In [25]:
print(array_1d[2:]) # Slicing third element onwards

[3 4]


In [26]:
array_1d[:3] # Slicing first three

array([1, 2, 3])

In [29]:
array_1d[2:5] # Slicing 3rd element to 5th element

array([3, 4])

In [30]:
array_1d[0::2]  #Subset starting from '0' with increment of '2'.

array([1, 3])

#### Iterating through np arrays: Arrays are ideally not meant to be iterated.

In [31]:
for i in array_1d:
      print(i**2)

1
4
9
16


### Time Stamp in python:

In [33]:
import time
time.time()  # Return the time in seconds

1536726076.7555306

## Basic operations on np arrays:

In [40]:
a=np.array([[1,2],[3,4]])

b=np.array([3,4,5,6])

arr=np.array([6,7,8,9])

arr1=np.array([5,6,7,8])

arr.reshape(2,2) # Reshapes an array

array([[6, 7],
       [8, 9]])

In [41]:
a.T # Transpose a np array

array([[1, 3],
       [2, 4]])

In [49]:
np.hstack((arr,arr1) ) # Horizontal stacking

array([6, 7, 8, 9, 5, 6, 7, 8])

In [48]:
np.vstack((arr,arr1)) #Vertical stacking

array([[6, 7, 8, 9],
       [5, 6, 7, 8]])

## Mathematical Operations on np arrays:

In [50]:
a=0.5

np.sin(a) # Print sine of one angle

0.479425538604203

In [51]:
np.cos(a) # Print cosine of one angle

0.8775825618903728

In [52]:
np.tan(a) # Print tangent of one angle

0.5463024898437905

In [53]:
np.exp(a) # Calculate the exponential of all elements in input array

1.6487212707001282

In [54]:
np.log(a) # Returns the natural logarithm

-0.6931471805599453

## Basic linear operations on np arrays: Numpy provides np.linalg package to apply the following linear algebra operations.

In [55]:
a= [[80,75,85],[75,80,75],[80,80,80]]

b=[[1,2,3,4],[5,6,7,8],[4,5,6,7]]


np.linalg.inv(a) # Returns the inverse of a matrix

array([[-2.00000000e-01, -4.00000000e-01,  5.87500000e-01],
       [ 5.37204689e-18,  2.00000000e-01, -1.87500000e-01],
       [ 2.00000000e-01,  2.00000000e-01, -3.87500000e-01]])

In [56]:
np.linalg.det(a) # Determinant of a matrix

-1999.9999999999998

In [57]:
np.linalg.eig(a) # Returns the eigen values and eigen vectors of a matrix

(array([236.68997441,  -1.68997441,   5.        ]),
 array([[-5.85824901e-01, -7.74431046e-01,  7.07106781e-01],
        [-5.60562596e-01,  1.45796315e-01, -7.07106781e-01],
        [-5.85302283e-01,  6.15629750e-01, -3.37181792e-16]]))

In [58]:
np.dot(a,b) # Multiply matrices using dot product

array([[ 795, 1035, 1275, 1515],
       [ 775, 1005, 1235, 1465],
       [ 800, 1040, 1280, 1520]])

User Defined Function: Whenever we are applying user defined function, it should be applied in a vectorized way.

In [59]:
f=np.vectorize(lambda x: x/(x+1))

f(arr)

array([0.85714286, 0.875     , 0.88888889, 0.9       ])

#### Numpy Indexing


In [2]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank, while using only slices yields an array of the same rank as the original array.

In [3]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [4]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


#### Integer Indexing: 
When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array.

In [5]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"


[1 4 5]
[1 4 5]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [6]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

# Create an array of indices
b = np.array([0, 2, 0, 1])
# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


#### Boolean array indexing: 
Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. 

In [7]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)
print(bool_idx) 

print(a[bool_idx])  # We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx



[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


#### Brodcasting:
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

In [8]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [9]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


#### Applications of broadcasting:

In [10]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)


[[ 4  5]
 [ 8 10]
 [12 15]]
